---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: facto-deployment 
spec:
  selector:
    matchLabels:
      app: facto-deployment
  replicas: 3
  template:
    metadata:
      labels:
        app: facto-deployment
    spec:
      containers:
      - name: facto-deployment
        image: facto-docker
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
